// Page Components
const Pages = {
    // Login Page
    login: () => {
        return `
            <div class="container">
                <div class="logo-container">
                    <img src="images/logo.png" alt="Reel Cinemas by Emaar" class="logo">
                </div>
                
                <div class="card">
                    <h1>Reel Technical Operations</h1>
                    <p class="subtitle">Select User Type</p>
                    
                    <div class="button-group">
                        <button class="btn btn-primary btn-large" onclick="App.selectUserType('Admin')">
                            Admin
                        </button>
                        <button class="btn btn-primary btn-large" onclick="App.selectUserType('Technician')">
                            Technician
                        </button>
                    </div>
                </div>
            </div>
        `;
    },
    
    // Password Page
    password: () => {
        const userType = sessionStorage.getItem('userType') || 'User';
        return `
            <div class="container">
                <div class="logo-container">
                    <img src="images/logo.png" alt="Reel Cinemas by Emaar" class="logo">
                </div>
                
                <div class="card">
                    <h1>${userType} Login</h1>
                    
                    <form id="loginForm" onsubmit="App.handleLogin(event)">
                        <div class="form-group">
                            <label for="password">Password</label>
                            <input type="password" id="password" class="input-field" required autofocus>
                        </div>
                        
                        <div id="errorMessage" class="error-message"></div>
                        
                        <div class="button-group">
                            <button type="submit" class="btn btn-primary btn-large">
                                Login
                            </button>
                            <button type="button" class="btn btn-secondary" onclick="Router.navigate('login')">
                                Back
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        `;
    },
    
    // Timeslot Page
    timeslot: () => {
        return `
            <div class="container">
                <div class="logo-container">
                    <img src="images/logo.png" alt="Reel Cinemas by Emaar" class="logo">
                </div>
                
                <div class="card">
                    <h1>Select Timeslot</h1>
                    <p class="subtitle">Choose your operation timeslot</p>
                    
                    <div class="button-group">
                        <button id="slot7am" class="btn btn-primary btn-large" onclick="App.selectTimeslot('7am')">
                            7:00 AM
                        </button>
                        <button id="slot3pm" class="btn btn-primary btn-large" onclick="App.selectTimeslot('3pm')">
                            3:00 PM
                        </button>
                        <button id="slot10pm" class="btn btn-primary btn-large" onclick="App.selectTimeslot('10pm')">
                            10:00 PM
                        </button>
                    </div>
                    
                    <div class="current-time">
                        Current Time: <span id="currentTime"></span>
                    </div>
                    
                    <button class="btn btn-secondary" onclick="App.logout()">
                        Logout
                    </button>
                </div>
            </div>
        `;
    },
    
    // Operations Page
operations: () => {
    const timeslot = sessionStorage.getItem('timeslot') || '';
    const userType = sessionStorage.getItem('userType') || '';
    const isAdmin = userType === 'Admin';
    
    return `
        <div class="container">
            
            <div class="card operations-card">
                <h1>Technical Operations</h1>
                <p class="subtitle">Timeslot: <span id="timeslotDisplay">${CONFIG.TIMESLOTS[timeslot]?.label || timeslot}</span></p>
                
                <div class="operations-grid" id="operationsGrid">
                    <!-- Buttons will be generated by JavaScript -->
                </div>
                
                <div class="control-buttons">
                    <button class="btn btn-success" onclick="App.showSaveModal()">
                        Save
                    </button>
                    <button class="btn btn-secondary" onclick="Router.navigate('timeslot')">
                        Back to Homepage
                    </button>
                    <button class="btn btn-info" onclick="App.downloadReport()">
                        Download Report
                    </button>
                    ${isAdmin ? '<button class="btn btn-danger" onclick="App.deleteLogs()">Delete Logs</button>' : ''}
                </div>
            </div>
        </div>
        
        <!-- Status Popup Modal -->
        <div id="statusModal" class="modal">
            <div class="modal-content">
                <h2>Set Status</h2>
                <p id="modalButtonName"></p>
                <div class="modal-buttons">
                    <button class="btn btn-success" onclick="App.setStatus('Active')">
                        Active
                    </button>
                    <button class="btn btn-danger" onclick="App.setStatus('In-Active')">
                        In-Active
                    </button>
                    <button class="btn btn-secondary" onclick="App.closeModal()">
                        Cancel
                    </button>
                </div>
            </div>
        </div>
        
        <!-- Technician Name Modal -->
        <div id="technicianModal" class="modal">
            <div class="modal-content">
                <h2>Enter Technician Name</h2>
                <form id="technicianForm" onsubmit="App.handleSaveWithName(event)">
                    <div class="form-group">
                        <label for="technicianName">Technician Name</label>
                        <input type="text" id="technicianName" class="input-field" required autofocus>
                    </div>
                    <div class="modal-buttons">
                        <button type="submit" class="btn btn-success">
                            Save Operations
                        </button>
                        <button type="button" class="btn btn-secondary" onclick="App.closeTechnicianModal()">
                            Cancel
                        </button>
                    </div>
                </form>
            </div>
        </div>
    `;
}
};